# build environment
FROM node:12.2.0-alpine as build
RUN mkdir "frontend"
WORKDIR /frontend
ENV PATH /frontend/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install --silent
RUN npm install @vue/cli@3.7.0 -g
COPY . /frontend

RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /frontend/dist /usr/share/nginx/html
