"""init3

Revision ID: 14e358e4a01b
Revises: c06f605d080f
Create Date: 2022-12-21 19:34:49.427042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e358e4a01b'
down_revision = 'c06f605d080f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'jobs', ['email'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'jobs', type_='unique')
    # ### end Alembic commands ###
