"""init2

Revision ID: ba4d1e5a2d76
Revises: 94d7b2722dea
Create Date: 2023-01-08 00:07:08.990938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4d1e5a2d76'
down_revision = '94d7b2722dea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
