"""job relation to user added viewonly

Revision ID: 2132b5ebbe7d
Revises: 548625a245ac
Create Date: 2023-02-25 12:03:49.238073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2132b5ebbe7d'
down_revision = '548625a245ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
