"""avatar column added to users model

Revision ID: 31692604b825
Revises: 637ce34623ce
Create Date: 2023-04-10 17:09:47.268328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31692604b825'
down_revision = '637ce34623ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
