"""added enum category

Revision ID: 548625a245ac
Revises: decc7e1f4e78
Create Date: 2023-02-24 09:47:13.464110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from schemas.job import JobCategory

# revision identifiers, used by Alembic.
revision = '548625a245ac'
down_revision = 'decc7e1f4e78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    jobcategory = postgresql.ENUM(JobCategory, name="jobcategory")
    jobcategory.create(op.get_bind(), checkfirst=True)
    op.add_column('jobs', sa.Column('category', jobcategory, server_default='miscellaneous', nullable=False))
    # op.add_column('jobs', sa.Column('category', sa.Enum('finance', 'marketing', 'agro', 'it', 'metallurgy', 'medicine', 'construction', 'building', 'services', 'miscellaneous', name='jobcategory'), server_default='miscellaneous', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'category')
    jobcategory = postgresql.ENUM(JobCategory, name="jobcategory")
    jobcategory.drop(op.get_bind())
    # ### end Alembic commands ###
