"""vacancies field corrected

Revision ID: 637ce34623ce
Revises: b4dca7b57247
Create Date: 2023-04-06 01:14:41.532505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637ce34623ce'
down_revision = 'b4dca7b57247'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
