"""job relation to appliers added viewonly

Revision ID: 88fcb504cf51
Revises: 2132b5ebbe7d
Create Date: 2023-02-25 12:07:48.075861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fcb504cf51'
down_revision = '2132b5ebbe7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
