"""resume column added to users model

Revision ID: a5e9dd9cf080
Revises: 31692604b825
Create Date: 2023-04-10 20:55:44.884510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e9dd9cf080'
down_revision = '31692604b825'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume')
    # ### end Alembic commands ###
