"""is_active changed

Revision ID: b4dca7b57247
Revises: 57b640a350b4
Create Date: 2023-04-05 17:24:36.460284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4dca7b57247'
down_revision = '57b640a350b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'is_expired')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('is_expired', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
