"""init3

Revision ID: f146c4943654
Revises: ba4d1e5a2d76
Create Date: 2023-01-08 00:09:03.075313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f146c4943654'
down_revision = 'ba4d1e5a2d76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
